### ISSUE TITLE
How to deal with 'mean' in a variable name

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [danholdaway/eva#33]
If for example, someone wants:

` experiment::ObsValue::${variable}-experiment::hofx_y_mean_xb0::${variable}`

like from the output from the ensemble application(s), eva will fail.

It finds 'mean' and tries to separate it out, even though it is part of the variable name. Can we 'escape' a keyword in the variable name somehow?

Thanks to @weihuang-jedi for finding this.

**Comment by danholdaway** [comment]
Yeah I guess I put that feature in as I was putting in all the mathematical functions and was thinking people might want to compute means (rms). Since that isn't being used I would suggest removing mean (and square root) for now. It wasn't clear to me that it would actually work. I just put it in so it wouldn't be forgotten about. The change would be to https://github.com/danholdaway/eva/blob/a5a784953479132080fa3a2ea5b9e9d3dc08cd68/src/eva/transforms/arithmetic.py#L53 Remove `|mean|sqrt`

**Comment by CoryMartin-NOAA** [comment]
It also doesn't seem to like it when a variable ends with a number (specifically 0)... not sure why that is. It seems like for some reason with `|mean|sqrt` removed now it splits like this:
`['experiment::ObsValue::surface_pressure', 'experiment::hofx_y_mean_xb', '::surface_pressure']`

I'm looking now into figuring out why, but I'm not very good with regex.

**Comment by CoryMartin-NOAA** [comment]
oh, @danholdaway I see, the very last part `\d` matches for any number. So this means variables/groups cannot have numbers in them. This is probably a big problem for our 'arithmetic interpreter'... Perhaps we need our own escape character to put in the input string for numbers? Force them to be inside parentheses?

**Comment by danholdaway** [comment]
Yeah, numbers are needed in case you want to double a variable or divide or raise to the power. What we could do is have a rename in the variable during the read part?

**Comment by CoryMartin-NOAA** [comment]
So looking more closely, I think numbers are fine. This was *splitting* by numbers, which it shouldn't do that I don't think. The numbers should be treated like a collection::group::variable is and then parsed to see if it is a string or a number. But I think this might require more thought/designing

**Comment by danholdaway** [comment]
OK. I agree with taking it out. Since there isn't a use case at the moment. But the splitting allowed for e.g. col::gro:var ^ 2 I think. We'll look at it if the need arises.

**Comment by weihuang-jedi** [comment]
Tried change hofx_y_mean_xb0 to JEDIHofX, then run, but got error:

bash-4.2$ eva ps-only.yaml
INFO EvaSetup: Starting Eva
INFO IodaObsSpace:   Initializing eva IodaObsSpace object
INFO EvaSetup: Running execute for IodaObsSpace
Traceback (most recent call last):
  File "/work2/noaa/gsienkf/weihuang/anaconda3/bin/eva", line 8, in <module>
    sys.exit(main())
  File
"/work2/noaa/gsienkf/weihuang/anaconda3/lib/python3.9/site-packages/eva/eva_base.py",
line 205, in main
    eva(config_file)
  File
"/work2/noaa/gsienkf/weihuang/anaconda3/lib/python3.9/site-packages/eva/eva_base.py",
line 165, in eva
    eva_data_object.execute(data_collections)
  File
"/work2/noaa/gsienkf/weihuang/anaconda3/lib/python3.9/site-packages/eva/data/ioda_obs_space.py",
line 147, in execute
    ds_groups = ds_groups.merge(ds)
  File
"/work2/noaa/gsienkf/weihuang/anaconda3/lib/python3.9/site-packages/xarray/core/dataset.py",
line 4326, in merge
    merge_result = dataset_merge_method(
  File
"/work2/noaa/gsienkf/weihuang/anaconda3/lib/python3.9/site-packages/xarray/core/merge.py",
line 951, in dataset_merge_method
    return merge_core(
  File
"/work2/noaa/gsienkf/weihuang/anaconda3/lib/python3.9/site-packages/xarray/core/merge.py",
line 634, in merge_core
    aligned = deep_align(
  File
"/work2/noaa/gsienkf/weihuang/anaconda3/lib/python3.9/site-packages/xarray/core/alignment.py",
line 435, in deep_align
    aligned = align(
  File
"/work2/noaa/gsienkf/weihuang/anaconda3/lib/python3.9/site-packages/xarray/core/alignment.py",
line 367, in align
    new_obj = obj.reindex(
  File
"/work2/noaa/gsienkf/weihuang/anaconda3/lib/python3.9/site-packages/xarray/core/dataset.py",
line 2943, in reindex
    return self._reindex(
  File
"/work2/noaa/gsienkf/weihuang/anaconda3/lib/python3.9/site-packages/xarray/core/dataset.py",
line 2972, in _reindex
    variables, indexes = alignment.reindex_variables(
  File
"/work2/noaa/gsienkf/weihuang/anaconda3/lib/python3.9/site-packages/xarray/core/alignment.py",
line 584, in reindex_variables
    raise ValueError(
ValueError: cannot reindex or align along dimension 'nlocs' because the
index has duplicate values
bash-4.2$ pwd
/home/weihuang/use-eva

What is the problem here?

**Comment by CoryMartin-NOAA** [comment]
@weihuang-jedi this looks like the issue we saw before where `nlocs` are duplicated (all 0 values). `JEDIHofX` is not a variable by default, did you create that one?

**Comment by weihuang-jedi** [comment]
JEDIHofX was created to replace hofx_y_mean_xb0.
I also tried remove variable nlocs, which got the same error.

**Comment by CoryMartin-NOAA** [comment]
@weihuang-jedi after the fix in #34 , your yaml from yesterday works for me as is. See `/home/cmartin/use-eva` on orion

**Comment by weihuang-jedi** [comment]
This is great. I tried upgrade eva, and re-run, and it worked.
Thank you both!

**Comment by weihuang-jedi** [comment]
Cory,

Attached are plots generated.

Here I few questions:

In plot:
gsi_hofx_vs_jedi_hofx_surf_surface_pressure.png
<https://mail.google.com/mail/u/0?ui=2&ik=9a02436ce6&attid=0.2&permmsgid=msg-a:r-1580839665198614997&view=att&disp=safe&realattid=f_l4q1hict0>,
and
gsi_hofx_vs_obs_surf_surface_pressure.png
<https://mail.google.com/mail/u/0?ui=2&ik=9a02436ce6&attid=0.1&permmsgid=msg-a:r-1580839665198614997&view=att&disp=safe&realattid=f_l4q1hid81>,
and
jedi_hofx_vs_obs_surf_surface_pressure.png
<https://mail.google.com/mail/u/0?ui=2&ik=9a02436ce6&attid=0.4&permmsgid=msg-a:r-1580839665198614997&view=att&disp=safe&realattid=f_l4q1hp3c3>
,

Can we specify a range, we see one start from 30000, two from 60000.

For plot:
gsi_omb_vs_jedi_omb_surf_surface_pressure.png
<https://mail.google.com/mail/u/0?ui=2&ik=9a02436ce6&attid=0.3&permmsgid=msg-a:r-1580839665198614997&view=att&disp=safe&realattid=f_l4q1hid92>
,

we see x range of -20000 to 60000, and y range -30000 to 20000. some of
those values did not like OMB values.

Thanks,

**Comment by CoryMartin-NOAA** [comment]
@weihuang-jedi there are no plots attached to this. You can't attach plots in a reply to GitHub through email, you need to put them in the github issue. Seeing as how this isn't related to this issue though, I suggest emailing them separately.

**Comment by weihuang-jedi** [comment]
Made change:

bash-4.2$ git diff src/eva/transforms/arithmetic.py
diff --git a/src/eva/transforms/arithmetic.py
b/src/eva/transforms/arithmetic.py
index a09f3fb..cb921e8 100644
--- a/src/eva/transforms/arithmetic.py
+++ b/src/eva/transforms/arithmetic.py
@@ -50,7 +50,8 @@ def arithmetic(config, data_collections):
                 expression = ''.join(expression.split())

                 # Split math equation
-                expression_elements =
re.split(r'\(|\)|-|\*|\+|\/|mean|sqrt|\d', expression)
+                #expression_elements =
re.split(r'\(|\)|-|\*|\+|\/|mean|sqrt|\d', expression)
+                expression_elements =
re.split(r'\(|\)|-|\*|\+|\/|sqrt|\d', expression)

                 # Remove empty elements and duplicates from expression
elements
                 expression_elements =
remove_empty_from_list_of_strings(expression_elements)

then do install:

pip install --prefix=/work2/noaa/gsienkf/weihuang/anaconda3 .

Still got error:

bash-4.2$ eva ps-only.yaml
INFO EvaSetup: Starting Eva
INFO IodaObsSpace:   Initializing eva IodaObsSpace object
INFO EvaSetup: Running execute for IodaObsSpace
INFO DataCollections:
--------------------------------------------------------------------------------
INFO DataCollections: Collections available:
INFO DataCollections:
INFO DataCollections: Collection name: experiment
INFO DataCollections:
INFO DataCollections:  Dimensions:
INFO DataCollections:   nlocs: 148197
INFO DataCollections:
INFO DataCollections:  Coordinates:
INFO DataCollections:   nlocs
INFO DataCollections:
INFO DataCollections:  Data (group::variable):
INFO DataCollections:   ObsValue::surface_pressure        (float32) |
Min=+5.7140e+04, Max=+1.0667e+05, RMS=+9.7927e+04
INFO DataCollections:   hofx_y_mean_xb0::surface_pressure (float32) |
Min=+5.6864e+04, Max=+1.0388e+05, RMS=+9.7855e+04
INFO DataCollections:   EffectiveQC0::surface_pressure    (int32  ) | Min=
        +0, Max=        +15,
INFO DataCollections:   GsiHofX::surface_pressure         (float32) |
Min=+5.4909e+04, Max=+1.0401e+05, RMS=+9.7043e+04
INFO DataCollections:   GsiEffectiveQC::surface_pressure  (int32  ) | Min=
        +0, Max=         +1,
INFO DataCollections:   MetaData::air_pressure            (float32) |
Min=+5.7140e+04, Max=+1.0667e+05, RMS=+9.7927e+04
INFO DataCollections:   MetaData::dateTime                (int64  ) |
Min=+5.7140e+04, Max=+1.0667e+05, RMS=+9.7927e+04
INFO DataCollections:   MetaData::height                  (float32) |
Min=-2.7000e+01, Max=+4.7010e+03, RMS=+6.2043e+02
INFO DataCollections:   MetaData::latitude                (float32) |
Min=-6.7800e+00, Max=+8.3630e+01, RMS=+4.5228e+01
INFO DataCollections:   MetaData::longitude               (float32) |
Min=+0.0000e+00, Max=+3.5993e+02, RMS=+2.2294e+02
INFO DataCollections:   MetaData::station_elevation       (float32) |
Min=-2.7000e+01, Max=+4.7010e+03, RMS=+6.2043e+02
INFO DataCollections:   MetaData::station_id              (object ) |
Min=-2.7000e+01, Max=+4.7010e+03, RMS=+6.2043e+02
INFO DataCollections:
--------------------------------------------------------------------------------
INFO TransformDriver:   Initializing eva TransformDriver object
INFO EvaSetup: Running execute for TransformDriver
ABORT ArithmeticTransform: split_collectiongroupvariable received
'{collectiongroupvariable}' but it has an incorrect format. Expecing
'collection::group::variable'.
ABORT

bash-4.2$ pwd
/home/weihuang/use-eva
